apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: surfersweb
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: surferslookout
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: python
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: surfersweb
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/initial-scale: "1"
        autoscaling.knative.dev/max-scale: "50"
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/scale-down-delay: 2s
        autoscaling.knative.dev/target: "60"
        autoscaling.knative.dev/window: 10s
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"surferslookout","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/language":"python","apps.tanzu.vmware.com/workload-type":"web"},"name":"surfersweb","namespace":"alpha"},"spec":{"env":[{"name":"GOOGLE_API_KEY","value":"AIzaSyClGDVij1cDFxSg9T034eayd8cZgnljRYA"}],"params":[{"name":"clusterBuilder","value":"default"},{"name":"annotations","value":{"autoscaling.knative.dev/initial-scale":"1","autoscaling.knative.dev/max-scale":"50","autoscaling.knative.dev/metric":"rps","autoscaling.knative.dev/min-scale":"1","autoscaling.knative.dev/scale-down-delay":"2s","autoscaling.knative.dev/target":"60","autoscaling.knative.dev/window":"10s"}},{"name":"git_user_email","value":"davidlloyd0@gmail.com"},{"name":"git_user_name","value":"davlloyd"}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"v1","kind":"Secret","name":"surferslookout-db"}},{"name":"api","ref":{"apiVersion":"v1","kind":"Secret","name":"surfersweb-api"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/davlloyd/surfers-web"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: surferslookout
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/language: python
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: surfersweb
    spec:
      containers:
      - env:
        - name: GOOGLE_API_KEY
          value: AIzaSyClGDVij1cDFxSg9T034eayd8cZgnljRYA
        image: us.gcr.io/lloyd-266015/supply-chain/surfersweb-alpha@sha256:fad7b6eaf90054f2eea193aed3390aad2d351948895a0ac2a202a6fa12605951
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

